# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: ec2f042084fd396efaa214fb05119311fc4817007b5c96d65df0a5634130ce8989ec78e56239124976ba01d601ec32e0de69f85fdf0f76c8ce72b5d1a434c877

test:
  secret_key_base: b092530f65a336a94d4190b42ac45478ed930c0ebd2dc813e4a0edbb6b2a5e15a5c14940a0f7c6d01df803716ef47595309450fc9ce71900c2bcd4f6a82a928c

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
